src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups("publishable")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Groups("publishable")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ApiToken", mappedBy="user", orphanRemoval=true)
     */
    private $apiTokens;

    private $availableRoles = ['ROLE_USER', 'ROLE_ADMIN', 'ROLE_ROOT', 'ROLE_API_USER'];

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Resume", mappedBy="addedByUser", orphanRemoval=true)
     */
    private $resumes;

    public function __construct()
    {
        $this->apiTokens = new ArrayCollection();
        $this->resumes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml

    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|ApiToken[]
     */
    public function getApiTokens(): Collection
    {
        return $this->apiTokens;
    }

    public function addApiToken(ApiToken $apiToken): self
    {
        if (!$this->apiTokens->contains($apiToken)) {
            $this->apiTokens[] = $apiToken;
        }

        return $this;
    }

    /**
     * @param string $role
     * @return array
     */
    public function addRole($role)
    {
        if (false === in_array($role, $this->getAvailableRoles())) {
            return array(
                'message' => 'Given role is not allowed. Allowed are : ' . implode(' , ', $this->getAvailableRoles()),
                'status' => Response::HTTP_BAD_REQUEST
            );
        }

        $currentUserRoles = $this->getRoles();

        if (false === in_array($role, $currentUserRoles) && $role !== 'ROLE_USER') {
            array_push($currentUserRoles, $role);
            $this->setRoles($currentUserRoles);
            return array(
                'message' => sprintf('User %s has now the roles: %s', $this->email, implode(' , ', $this->getRoles())),
                'status' => Response::HTTP_OK
            );

        } else {
            return array(
                'message' => 'User already has this role',
                'status' => Response::HTTP_BAD_REQUEST,
            );
        }
    }

    /**
     * @param string $role
     * @return array
     */
    public function removeRole($role)
    {
        $currentUserRoles = $this->getRoles();

        if (false === in_array($role, $currentUserRoles) && $role !== 'ROLE_USER') {
            return array(
                'message' => 'User does not have this role',
                'status' => Response::HTTP_BAD_REQUEST,
            );
        } else {
            unset ($currentUserRoles[array_search($role,$currentUserRoles)]);
            $this->setRoles($currentUserRoles);
            return array(
                'message' => sprintf('User %s has now the roles: %s', $this->email, implode(' , ', $this->getRoles())),
                'status' => Response::HTTP_OK
            );
        }
    }

    /**
     * @return array
     */
    public function getAvailableRoles(): array
    {
        return $this->availableRoles;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Collection|Resume[]
     */
    public function getResumes(): Collection
    {
        return $this->resumes;
    }

    public function addResume(Resume $resume): self
    {
        if (!$this->resumes->contains($resume)) {
            $this->resumes[] = $resume;
            $resume->setAddedByUser($this);
        }

        return $this;
    }

    public function removeResume(Resume $resume): self
    {
        if ($this->resumes->contains($resume)) {
            $this->resumes->removeElement($resume);
            // set the owning side to null (unless already changed)
            if ($resume->getAddedByUser() === $this) {
                $resume->setAddedByUser(null);
            }
        }

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
        <!-- Bootstrap 4-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <!-- Font Awesome-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
              integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ"
              crossorigin="anonymous">
    {% endblock %}
    {% block JSLibraries %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    {% endblock %}
</head>
<body>
<header>
    <div class="container-fluid">
        <div class="row">
            <div class="well col-xs-12 col-sm-12 col-md-12 col-lg-12">
                {% block header %}
                    {% include asset('header.html.twig') %}
                {% endblock %}
            </div>
        </div>
    </div>
</header>
<div class="container-fluid">
    <div class="row" id="vueBody">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
            {% block leftMenu %}
                {% include asset('leftMenu.html.twig') %}
            {% endblock %}
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>
<footer>
    <div class="container-fluid well">
        {% block footer %}
            {% include asset('footer.html.twig') %}
        {% endblock %}
    </div>
</footer>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/footer.html.twig
<div>
    <div class="d-flex justify-content-center">
        {% for name,link in links.footerLinks %}
            <a href="{{ link }}" class="card-link">{{ name }}</a>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center">
        <span>Copyright Reza 2019 </span><i class="fa fa-copyright"></i>
    </div>
</div>

templates/header.html.twig
<nav class="navbar navbar-expand-lg navbar-dark black">
    <div class="container">
        <a class="navbar-brand" href="{{ path('home') }}" style="color: black"><strong>LOGO</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
                {% block navLinks %}
                    {% for name,link in links.headerLinks %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{path(link)}}" style="color: black">{{name}}
                            <span class="sr-only"></span></a>
                    </li>
                    {% endfor %}
                {% endblock %}

            </ul>
            {% if app.user %}
                <div class="checkbox mb-3">{{ app.user.username }} <a href="{{ path('app_logout') }}">Logout</a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>

templates/leftMenu.html.twig
<div class="list-group" id="leftMenu">
    {% for name,link in links.leftMenuLinks %}
        <a href="{{ path(link)}}" class="list-group-item list-group-item-action" v-on:click.prevent="getContent($event.target.href,$event)">{{ name }}</a>
    {% endfor %}
</div>